version: v2-alpha
description: Run of NumNet on {{.Env.DATA_DS}}
tasks:
  - image:
      beaker: {{.Env.IMG}}
    arguments:
      - sh
      - train_beaker.sh
      - 345
      - 5e-4
      - 1.5e-5
      - 5e-5
      - 0.01
    envVars:
      - name: DATA_DIR
        value: "/input/"
      - name: MODEL_DIR
        value: "/model/"
      - name: OUT_DIR
        value: "/output/"
    datasets:
      - mountPath: /model
        source:
          beaker: {{.Env.MODEL_DS}}
      - mountPath: /input
        source:
          beaker: {{.Env.DATA_DS}}
    result:
      path: /output
    resources:
      gpuCount: 1
    context:
      cluster: ai2/on-prem-aristo
      priority: normal
